config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "avatars/new" => "avatars#new"
  resources :avatars
  root to: redirect('/ideas')
  resources :ideas

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
    if user.blank?
      # not logged in
      cannot :manage, :all
    #basic_read_only
    #elsif user.authorize(:admin)
    elsif user.authorize == 'admin'
      # admin

      can :manage, :all

    #elsif user.authorize(:common)
    elsif user.authorize == 'common'
      
      can :update, Idea do |idea|
        (idea.user_id == user.id)
      end
  
      cannot :destroy, :all
      
      can :new, @avatar

      if user.ideas_count >= 1
        cannot :new, @idea
      end

    #elsif user.authorize(:rookie)
    elsif user.authorize == 'rookie'      
      cannot :manage, :all
        #basic_read_only
    end


    #protected

    #def basic_read_only
    #  can :read,    Idea
    #  can :list,    Idea
    #  can :search,  Idea
    #end

    def load_and_authorize_resource
      load_resource
      authorize_resource
    end

  end
end

app/models/avatar.rb
class Avatar < ActiveRecord::Base
  mount_uploader :head_portrait, PictureUploader

  belongs_to :user , class_name: "User" , foreign_key: :id
  
  
end

app/models/idea.rb
class Idea < ActiveRecord::Base
	mount_uploader :picture, PictureUploader

	belongs_to :user , :counter_cache => true


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable 信箱驗證, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  include Gravtastic
	gravtastic

  has_many :ideas
  has_one :avatar , foreign_key: "user_id" 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # 驗證是否登入
  before_action :authenticate_user!
  # 加入 strong_parameters 與 devise 整合的 hack
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  # Cancan
  rescue_from CanCan::AccessDenied do |exception| 
    redirect_to ideas_url, :alert => exception.message
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:name) }
  end


end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  before_action :authenticate_user!

  def index
  	@avatars = Avatar.all
  end

  def show
  end
 
  def new
    @avatar = Avatar.new
  end
   
  def edit
  end
 
  def create
  	# @avatar = current_user.avatar.new(avatar_params)
  	# why idea可以這樣寫這個不行ＱＱ
  	@avatar = Avatar.new(avatar_params)
    # 明明就差不多意思啊哭哭ㄇ
  	@avatar.user_id = current_user.id
    # ↑上面這段抓目前登入的user id 啦
    current_user.avatar_id = @avatar.id    

    respond_to do |format|
      if @avatar.save
        format.html { redirect_to ideas_path , notice: 'Avatar was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @avatar.errors, status: :unprocessable_entity }
      end
    end
  end
 
  def update
    respond_to do |format|
      if @avatar.update(avatar_params)
        format.html { redirect_to @idea, notice: 'Avatar was successfully updated.' }
        format.json { render :index, location: @idea  }
      else
        format.html { render :new }
        format.json { render json: @avatar.errors, status: :unprocessable_entity }
      end
    end
  end
 
  def destroy
  end

  private

  def avatar_params
    params.require(:avatar).permit(:nickname, :head_portrait , :user_id)
  end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # cancan
  # authorize_resource :idea
  # load_resource

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    authorize! :new, @idea 
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
    authorize! :update, @idea 
  end

  # POST /ideas
  # POST /ideas.json
  def create
  # @idea = Idea.new(idea_params)
  # 讓新增idea時可存入user id
    @idea = current_user.ideas.new(idea_params)
    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    #  @idea = current_user.ideas.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :description, :picture, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/avatars/new.html.erb
<h2>Avatar</h2>

  <%= simple_form_for(@avatar , :html => {:multipart => true}) do |f| %>

  <div class="field">  
    <%= f.label :nickname %><br />  
    <%= f.text_field :nickname %>  
  </div>  

  <div class="field">  
    <%= f.label :head_portrait %><br />  
    <%= image_tag(@avatar.picture_url(:bighead)) if @avatar.head_portrait? %>  
    <%= f.file_field :head_portrait %>  
    <%#= f.hidden_field :head_portrait_cache%>  
  </div>  

  <div class="actions">  
    <%= f.submit %>  
  </div>    

  <% end %>

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%#= image_tag(@idea.picture_url) if @idea.picture? %>
    <%= image_tag @idea.picture_url(:thumb)%>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ideas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.name %></td>
        <td><%= idea.description %></td>
        <%#td><%= idea.picture ></td%>
        <td><%= image_tag idea.picture_url(:small_thumb)%></td>
        <td><%= link_to 'Show', idea %></td>
        <td>
          <% if can? :update, idea %>
            <%= link_to 'Edit', edit_idea_path(idea) %>
          <% end %>
        </td>
        <td>
          <% if can? :destroy, idea %>
            <%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %> 
        </td>
         
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if can? :new, @idea %>
  <%= link_to 'New Idea', new_idea_path %>
<% end %> 

app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @idea.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @idea.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%#= @idea.picture %>
  <%= image_tag @idea.picture.url(:thumb)%>
</p>

<% if can? :update, @idea %>
<%= link_to 'Edit', edit_idea_path(@idea) %> |
<% end %>
<%= link_to 'Back', ideas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CreateAccount</title>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <%#Let it become perty #CSS %>
  <nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Just Create Account</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">TesT PaGe</a></li>
      </ul>
      
      <%#誒這個註解好麻煩，總之就是在nbar上加登入資訊啦%>
      <p class="navbar-text pull-right">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.name %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> |
          <%= link_to 'Edit Avatar', avatars_new_path, :class => 'navbar-link' %>
          
      <%#To use gravatar%>

          <span class="user-gravatar"><%= image_tag current_user.avatar.head_portrait_url %></span>

        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </p>

    </div>
  </div>
</nav>

</head>
<body>


<div class="container">
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <%= yield %>
</div>

</body>

<footer>
  <div class="container">
    Easy do it.  10/8/2015
  </div>
</footer>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

</html>